[metadata]
name = cnn-classifier
version = 0.1.0
description = Chicken disease classification package
author = Raj Singh
license = MIT
# If you have a README.md:
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
package_dir =
    = src
python_requires = >=3.8
include_package_data = True
install_requires =
    # put your runtime deps here, e.g.
    numpy
    pandas
    scikit-learn

[options.packages.find]
where = src

[options.extras_require]
dev =
    pytest
    black
